model: 'BiGRU'
model_kwargs:
  n_labels: ~
  n_cats: ~
  embedding_dim: 100
  embedding_matrix: ~
  label_embedding_matrix: ~
  cat_embedding_matrix: ~
  code2cat_map: ~
  hidden_size: 512
  RNN_type: 'GRU'
  bidir: True
  dropout_p: 0.3
  att_module: ~
  scale: True
  multihead: ~
  num_heads: ~
  gamma: ~
train_kwargs:
  doc_max_len: ~
  batch_size: 32
  epochs: 100
  patience: 10
  lr: 0.0001
  optimizer: 'Adam'
  multilabel: True
  alignment: False

