model: 'BiLSTM'
model_kwargs:
  n_labels: ~
  n_cats: ~
  embedding_dim: 100
  embedding_scaling: 0.5
  token_embedding_matrix: ~
  label_embedding_matrix: ~
  cat_embedding_matrix: ~
  code2cat_map: ~
  hidden_size: 512
  RNN_type: 'LSTM'
  bidir: True
  dropout_p: 0.15
  att_module: ~
  scale: True
  multihead: ~
  num_heads: ~
train_kwargs:
  doc_max_len: ~
  batch_size: 32
  epochs: 100
  patience: 10
  lr: 0.0001
  quartiles: False
  individual: False

