model: 'CNN'
model_kwargs:
  n_labels: ~
  n_cats: ~
  embedding_dim: 100
  embedding_matrix: ~
  label_embedding_matrix: ~
  cat_embedding_matrix: ~
  code2cat_map: ~
  window_sizes: [3, 4, 5]
  n_filters: [500, 500, 500]
  dropout_p: 0.3
  att_module: ~
  scale: True
  multihead: False
  num_heads: ~
  gamma: ~
train_kwargs:
  doc_max_len: ~
  batch_size: 16
  epochs: 100
  patience: 10
  lr: 0.0001
  optimizer: 'Adam'
  multilabel: True


